server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/evently}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone=Asia/Kolkata:
grpc:
  server:
    port: 9090

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [traceId=%X{traceId}] [%thread] %logger{36} - %msg%n"